# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patrikUI1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(18, 30, 771, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.portsWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.portsWidget.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.portsWidget.setObjectName("portsWidget")
        self.verticalLayout.addWidget(self.portsWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout.addWidget(self.ConnectButton)
        self.refreshButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 171, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CalibrationButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.CalibrationButton.setObjectName("CalibrationButton")
        self.verticalLayout_2.addWidget(self.CalibrationButton)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.StartButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout_2.addWidget(self.StartButton)
        self.DrinkButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.DrinkButton.setObjectName("DrinkButton")
        self.verticalLayout_2.addWidget(self.DrinkButton)
        self.SelfPourButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SelfPourButton.setObjectName("SelfPourButton")
        self.verticalLayout_2.addWidget(self.SelfPourButton)
        self.PourButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PourButton.setObjectName("PourButton")
        self.verticalLayout_2.addWidget(self.PourButton)
        self.WagButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.WagButton.setObjectName("WagButton")
        self.verticalLayout_2.addWidget(self.WagButton)
        self.NiceButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.NiceButton.setObjectName("NiceButton")
        self.verticalLayout_2.addWidget(self.NiceButton)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(600, 10, 191, 401))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.head_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.head_min.setAutoRepeat(True)
        self.head_min.setObjectName("head_min")
        self.horizontalLayout_12.addWidget(self.head_min)
        self.head_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.head_plus.setAutoRepeat(True)
        self.head_plus.setObjectName("head_plus")
        self.horizontalLayout_12.addWidget(self.head_plus)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.neck_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.neck_min.setAutoRepeat(True)
        self.neck_min.setObjectName("neck_min")
        self.horizontalLayout_13.addWidget(self.neck_min)
        self.neck_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.neck_plus.setAutoRepeat(True)
        self.neck_plus.setObjectName("neck_plus")
        self.horizontalLayout_13.addWidget(self.neck_plus)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_17.addWidget(self.label_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rollR_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.rollR_min.setAutoRepeat(True)
        self.rollR_min.setObjectName("rollR_min")
        self.horizontalLayout_2.addWidget(self.rollR_min)
        self.rollR_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.rollR_plus.setAutoRepeat(True)
        self.rollR_plus.setObjectName("rollR_plus")
        self.horizontalLayout_2.addWidget(self.rollR_plus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.shold2R_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold2R_min.setAutoRepeat(True)
        self.shold2R_min.setObjectName("shold2R_min")
        self.horizontalLayout_3.addWidget(self.shold2R_min)
        self.shold2R_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold2R_plus.setAutoRepeat(True)
        self.shold2R_plus.setObjectName("shold2R_plus")
        self.horizontalLayout_3.addWidget(self.shold2R_plus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.shold1R_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold1R_min.setAutoRepeat(True)
        self.shold1R_min.setObjectName("shold1R_min")
        self.horizontalLayout_5.addWidget(self.shold1R_min)
        self.shold1R_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold1R_plus.setAutoRepeat(True)
        self.shold1R_plus.setObjectName("shold1R_plus")
        self.horizontalLayout_5.addWidget(self.shold1R_plus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.armR_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.armR_min.setAutoRepeat(True)
        self.armR_min.setObjectName("armR_min")
        self.horizontalLayout_4.addWidget(self.armR_min)
        self.armR_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.armR_plus.setAutoRepeat(True)
        self.armR_plus.setObjectName("armR_plus")
        self.horizontalLayout_4.addWidget(self.armR_plus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.handR_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.handR_min.setAutoRepeat(True)
        self.handR_min.setObjectName("handR_min")
        self.horizontalLayout_6.addWidget(self.handR_min)
        self.handR_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.handR_plus.setAutoRepeat(True)
        self.handR_plus.setObjectName("handR_plus")
        self.horizontalLayout_6.addWidget(self.handR_plus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rollL_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.rollL_min.setAutoRepeat(True)
        self.rollL_min.setObjectName("rollL_min")
        self.horizontalLayout_7.addWidget(self.rollL_min)
        self.rollL_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.rollL_plus.setAutoRepeat(True)
        self.rollL_plus.setObjectName("rollL_plus")
        self.horizontalLayout_7.addWidget(self.rollL_plus)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.shold2L_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold2L_min.setAutoRepeat(True)
        self.shold2L_min.setObjectName("shold2L_min")
        self.horizontalLayout_8.addWidget(self.shold2L_min)
        self.shold2L_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold2L_plus.setAutoRepeat(True)
        self.shold2L_plus.setObjectName("shold2L_plus")
        self.horizontalLayout_8.addWidget(self.shold2L_plus)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.shold1L_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold1L_min.setAutoRepeat(True)
        self.shold1L_min.setObjectName("shold1L_min")
        self.horizontalLayout_9.addWidget(self.shold1L_min)
        self.shold1L_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.shold1L_plus.setAutoRepeat(True)
        self.shold1L_plus.setObjectName("shold1L_plus")
        self.horizontalLayout_9.addWidget(self.shold1L_plus)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.armL_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.armL_min.setAutoRepeat(True)
        self.armL_min.setObjectName("armL_min")
        self.horizontalLayout_10.addWidget(self.armL_min)
        self.armL_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.armL_plus.setAutoRepeat(True)
        self.armL_plus.setObjectName("armL_plus")
        self.horizontalLayout_10.addWidget(self.armL_plus)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.handL_min = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.handL_min.setAutoRepeat(True)
        self.handL_min.setObjectName("handL_min")
        self.horizontalLayout_11.addWidget(self.handL_min)
        self.handL_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.handL_plus.setAutoRepeat(True)
        self.handL_plus.setObjectName("handL_plus")
        self.horizontalLayout_11.addWidget(self.handL_plus)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(200, 10, 381, 401))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.infoBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        self.infoBrowser.setObjectName("infoBrowser")
        self.verticalLayout_7.addWidget(self.infoBrowser)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.detach_all_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.detach_all_Button.setObjectName("detach_all_Button")
        self.horizontalLayout_15.addWidget(self.detach_all_Button)
        self.detach_hands_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.detach_hands_Button.setObjectName("detach_hands_Button")
        self.horizontalLayout_15.addWidget(self.detach_hands_Button)
        self.attach_all_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.attach_all_Button.setObjectName("attach_all_Button")
        self.horizontalLayout_15.addWidget(self.attach_all_Button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.next_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.next_Button.setObjectName("next_Button")
        self.horizontalLayout_16.addWidget(self.next_Button)
        self.save_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.save_Button.setObjectName("save_Button")
        self.horizontalLayout_16.addWidget(self.save_Button)
        self.testButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.testButton.setObjectName("testButton")
        self.horizontalLayout_16.addWidget(self.testButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.comboBox.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox.setItemText(1, _translate("MainWindow", "38400"))
        self.comboBox.setItemText(2, _translate("MainWindow", "57600"))
        self.comboBox.setItemText(3, _translate("MainWindow", "115200"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "CONNECTION"))
        self.CalibrationButton.setText(_translate("MainWindow", "CALIBRATION"))
        self.label_4.setText(_translate("MainWindow", "POSITIONS:"))
        self.StartButton.setText(_translate("MainWindow", "START"))
        self.DrinkButton.setText(_translate("MainWindow", "DRINK"))
        self.SelfPourButton.setText(_translate("MainWindow", "SELF POUR"))
        self.PourButton.setText(_translate("MainWindow", "POUR"))
        self.WagButton.setText(_translate("MainWindow", "WAG"))
        self.NiceButton.setText(_translate("MainWindow", "NICE"))
        self.label.setText(_translate("MainWindow", "HEAD:"))
        self.head_min.setText(_translate("MainWindow", "-"))
        self.head_plus.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "NECK:"))
        self.neck_min.setText(_translate("MainWindow", "-"))
        self.neck_plus.setText(_translate("MainWindow", "+"))
        self.label_5.setText(_translate("MainWindow", "RIGHT HAND:"))
        self.label_3.setText(_translate("MainWindow", "LEFT HAND:"))
        self.rollR_min.setText(_translate("MainWindow", "-"))
        self.rollR_plus.setText(_translate("MainWindow", "+"))
        self.shold2R_min.setText(_translate("MainWindow", "-"))
        self.shold2R_plus.setText(_translate("MainWindow", "+"))
        self.shold1R_min.setText(_translate("MainWindow", "-"))
        self.shold1R_plus.setText(_translate("MainWindow", "+"))
        self.armR_min.setText(_translate("MainWindow", "-"))
        self.armR_plus.setText(_translate("MainWindow", "+"))
        self.handR_min.setText(_translate("MainWindow", "-"))
        self.handR_plus.setText(_translate("MainWindow", "+"))
        self.rollL_min.setText(_translate("MainWindow", "-"))
        self.rollL_plus.setText(_translate("MainWindow", "+"))
        self.shold2L_min.setText(_translate("MainWindow", "-"))
        self.shold2L_plus.setText(_translate("MainWindow", "+"))
        self.shold1L_min.setText(_translate("MainWindow", "-"))
        self.shold1L_plus.setText(_translate("MainWindow", "+"))
        self.armL_min.setText(_translate("MainWindow", "-"))
        self.armL_plus.setText(_translate("MainWindow", "+"))
        self.handL_min.setText(_translate("MainWindow", "-"))
        self.handL_plus.setText(_translate("MainWindow", "+"))
        self.detach_all_Button.setText(_translate("MainWindow", "DETACH ALL"))
        self.detach_hands_Button.setText(_translate("MainWindow", "DETACH HANDS"))
        self.attach_all_Button.setText(_translate("MainWindow", "ATTACH ALL"))
        self.next_Button.setText(_translate("MainWindow", "NEXT"))
        self.save_Button.setText(_translate("MainWindow", "SAVE"))
        self.testButton.setText(_translate("MainWindow", "TEST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CALIBRATION"))

