# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patrikUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.portsWidget = QtWidgets.QListWidget(self.centralwidget)
        self.portsWidget.setGeometry(QtCore.QRect(20, 10, 181, 131))
        self.portsWidget.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.portsWidget.setObjectName("portsWidget")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(20, 140, 91, 32))
        self.ConnectButton.setObjectName("ConnectButton")
        self.CalibrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.CalibrationButton.setGeometry(QtCore.QRect(60, 210, 113, 32))
        self.CalibrationButton.setObjectName("CalibrationButton")
        self.DrinkButton = QtWidgets.QPushButton(self.centralwidget)
        self.DrinkButton.setGeometry(QtCore.QRect(60, 300, 113, 32))
        self.DrinkButton.setObjectName("DrinkButton")
        self.PourButton = QtWidgets.QPushButton(self.centralwidget)
        self.PourButton.setGeometry(QtCore.QRect(60, 320, 113, 32))
        self.PourButton.setObjectName("PourButton")
        self.SelfPourButton = QtWidgets.QPushButton(self.centralwidget)
        self.SelfPourButton.setGeometry(QtCore.QRect(60, 340, 113, 32))
        self.SelfPourButton.setObjectName("SelfPourButton")
        self.WagButton = QtWidgets.QPushButton(self.centralwidget)
        self.WagButton.setGeometry(QtCore.QRect(60, 360, 113, 32))
        self.WagButton.setObjectName("WagButton")
        self.NiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.NiceButton.setGeometry(QtCore.QRect(60, 380, 113, 32))
        self.NiceButton.setObjectName("NiceButton")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(60, 400, 113, 32))
        self.StartButton.setObjectName("StartButton")
        self.neck_min = QtWidgets.QPushButton(self.centralwidget)
        self.neck_min.setGeometry(QtCore.QRect(480, 120, 51, 32))
        self.neck_min.setAutoRepeat(True)
        self.neck_min.setObjectName("neck_min")
        self.neck_plus = QtWidgets.QPushButton(self.centralwidget)
        self.neck_plus.setGeometry(QtCore.QRect(520, 120, 51, 32))
        self.neck_plus.setAutoRepeat(True)
        self.neck_plus.setObjectName("neck_plus")
        self.head_min = QtWidgets.QPushButton(self.centralwidget)
        self.head_min.setGeometry(QtCore.QRect(480, 90, 51, 32))
        self.head_min.setAutoRepeat(True)
        self.head_min.setObjectName("head_min")
        self.head_plus = QtWidgets.QPushButton(self.centralwidget)
        self.head_plus.setGeometry(QtCore.QRect(520, 90, 51, 32))
        self.head_plus.setAutoRepeat(True)
        self.head_plus.setObjectName("head_plus")
        self.rollR_min = QtWidgets.QPushButton(self.centralwidget)
        self.rollR_min.setGeometry(QtCore.QRect(380, 160, 51, 32))
        self.rollR_min.setAutoRepeat(True)
        self.rollR_min.setObjectName("rollR_min")
        self.rollR_plus = QtWidgets.QPushButton(self.centralwidget)
        self.rollR_plus.setGeometry(QtCore.QRect(420, 160, 51, 32))
        self.rollR_plus.setAutoRepeat(True)
        self.rollR_plus.setObjectName("rollR_plus")
        self.shold2R_plus = QtWidgets.QPushButton(self.centralwidget)
        self.shold2R_plus.setGeometry(QtCore.QRect(390, 190, 51, 32))
        self.shold2R_plus.setAutoRepeat(True)
        self.shold2R_plus.setObjectName("shold2R_plus")
        self.shold2R_min = QtWidgets.QPushButton(self.centralwidget)
        self.shold2R_min.setGeometry(QtCore.QRect(350, 190, 51, 32))
        self.shold2R_min.setAutoRepeat(True)
        self.shold2R_min.setObjectName("shold2R_min")
        self.shold1R_plus = QtWidgets.QPushButton(self.centralwidget)
        self.shold1R_plus.setGeometry(QtCore.QRect(380, 220, 51, 32))
        self.shold1R_plus.setAutoRepeat(True)
        self.shold1R_plus.setObjectName("shold1R_plus")
        self.shold1R_min = QtWidgets.QPushButton(self.centralwidget)
        self.shold1R_min.setGeometry(QtCore.QRect(340, 220, 51, 32))
        self.shold1R_min.setAutoRepeat(True)
        self.shold1R_min.setObjectName("shold1R_min")
        self.armR_plus = QtWidgets.QPushButton(self.centralwidget)
        self.armR_plus.setGeometry(QtCore.QRect(380, 250, 51, 32))
        self.armR_plus.setAutoRepeat(True)
        self.armR_plus.setObjectName("armR_plus")
        self.armR_min = QtWidgets.QPushButton(self.centralwidget)
        self.armR_min.setGeometry(QtCore.QRect(340, 250, 51, 32))
        self.armR_min.setAutoRepeat(True)
        self.armR_min.setObjectName("armR_min")
        self.handR_plus = QtWidgets.QPushButton(self.centralwidget)
        self.handR_plus.setGeometry(QtCore.QRect(380, 280, 51, 32))
        self.handR_plus.setAutoRepeat(True)
        self.handR_plus.setObjectName("handR_plus")
        self.handR_min = QtWidgets.QPushButton(self.centralwidget)
        self.handR_min.setGeometry(QtCore.QRect(340, 280, 51, 32))
        self.handR_min.setAutoRepeat(True)
        self.handR_min.setObjectName("handR_min")
        self.rollL_plus = QtWidgets.QPushButton(self.centralwidget)
        self.rollL_plus.setGeometry(QtCore.QRect(630, 160, 51, 32))
        self.rollL_plus.setAutoRepeat(True)
        self.rollL_plus.setObjectName("rollL_plus")
        self.rollL_min = QtWidgets.QPushButton(self.centralwidget)
        self.rollL_min.setGeometry(QtCore.QRect(590, 160, 51, 32))
        self.rollL_min.setAutoRepeat(True)
        self.rollL_min.setObjectName("rollL_min")
        self.shold2L_plus = QtWidgets.QPushButton(self.centralwidget)
        self.shold2L_plus.setGeometry(QtCore.QRect(650, 190, 51, 32))
        self.shold2L_plus.setAutoRepeat(True)
        self.shold2L_plus.setObjectName("shold2L_plus")
        self.shold2L_min = QtWidgets.QPushButton(self.centralwidget)
        self.shold2L_min.setGeometry(QtCore.QRect(610, 190, 51, 32))
        self.shold2L_min.setAutoRepeat(True)
        self.shold2L_min.setObjectName("shold2L_min")
        self.shold1L_plus = QtWidgets.QPushButton(self.centralwidget)
        self.shold1L_plus.setGeometry(QtCore.QRect(660, 220, 51, 32))
        self.shold1L_plus.setAutoRepeat(True)
        self.shold1L_plus.setObjectName("shold1L_plus")
        self.shold1L_min = QtWidgets.QPushButton(self.centralwidget)
        self.shold1L_min.setGeometry(QtCore.QRect(620, 220, 51, 32))
        self.shold1L_min.setAutoRepeat(True)
        self.shold1L_min.setObjectName("shold1L_min")
        self.armL_plus = QtWidgets.QPushButton(self.centralwidget)
        self.armL_plus.setGeometry(QtCore.QRect(660, 250, 51, 32))
        self.armL_plus.setAutoRepeat(True)
        self.armL_plus.setObjectName("armL_plus")
        self.armL_min = QtWidgets.QPushButton(self.centralwidget)
        self.armL_min.setGeometry(QtCore.QRect(620, 250, 51, 32))
        self.armL_min.setAutoRepeat(True)
        self.armL_min.setObjectName("armL_min")
        self.handL_plus = QtWidgets.QPushButton(self.centralwidget)
        self.handL_plus.setGeometry(QtCore.QRect(660, 280, 51, 32))
        self.handL_plus.setAutoRepeat(True)
        self.handL_plus.setObjectName("handL_plus")
        self.handL_min = QtWidgets.QPushButton(self.centralwidget)
        self.handL_min.setGeometry(QtCore.QRect(620, 280, 51, 32))
        self.handL_min.setAutoRepeat(True)
        self.handL_min.setObjectName("handL_min")
        self.detach_all_Button = QtWidgets.QPushButton(self.centralwidget)
        self.detach_all_Button.setGeometry(QtCore.QRect(360, 380, 113, 32))
        self.detach_all_Button.setObjectName("detach_all_Button")
        self.detach_hands_Button = QtWidgets.QPushButton(self.centralwidget)
        self.detach_hands_Button.setGeometry(QtCore.QRect(480, 380, 113, 32))
        self.detach_hands_Button.setObjectName("detach_hands_Button")
        self.attach_all_Button = QtWidgets.QPushButton(self.centralwidget)
        self.attach_all_Button.setGeometry(QtCore.QRect(600, 380, 113, 32))
        self.attach_all_Button.setObjectName("attach_all_Button")
        self.save_Button = QtWidgets.QPushButton(self.centralwidget)
        self.save_Button.setGeometry(QtCore.QRect(410, 430, 113, 32))
        self.save_Button.setObjectName("save_Button")
        self.next_Button = QtWidgets.QPushButton(self.centralwidget)
        self.next_Button.setGeometry(QtCore.QRect(540, 430, 113, 32))
        self.next_Button.setObjectName("next_Button")
        self.senseBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.senseBrowser.setGeometry(QtCore.QRect(300, 10, 121, 51))
        self.senseBrowser.setObjectName("senseBrowser")
        self.distanceBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.distanceBrowser.setGeometry(QtCore.QRect(470, 10, 121, 51))
        self.distanceBrowser.setObjectName("distanceBrowser")
        self.timeBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.timeBrowser.setGeometry(QtCore.QRect(640, 10, 121, 51))
        self.timeBrowser.setObjectName("timeBrowser")
        self.infoBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoBrowser.setGeometry(QtCore.QRect(300, 320, 461, 51))
        self.infoBrowser.setObjectName("infoBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 70, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 70, 41, 16))
        self.label_3.setObjectName("label_3")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(110, 140, 91, 32))
        self.refreshButton.setObjectName("refreshButton")
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setGeometry(QtCore.QRect(60, 170, 113, 32))
        self.testButton.setObjectName("testButton")
        self.rateWidget = QtWidgets.QListWidget(self.centralwidget)
        self.rateWidget.setGeometry(QtCore.QRect(210, 10, 81, 131))
        self.rateWidget.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.rateWidget.setObjectName("rateWidget")
        item = QtWidgets.QListWidgetItem()
        self.rateWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.rateWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.rateWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.rateWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.CalibrationButton.setText(_translate("MainWindow", "Calibration"))
        self.DrinkButton.setText(_translate("MainWindow", "Drink"))
        self.PourButton.setText(_translate("MainWindow", "Pour"))
        self.SelfPourButton.setText(_translate("MainWindow", "SelfPour"))
        self.WagButton.setText(_translate("MainWindow", "Wag"))
        self.NiceButton.setText(_translate("MainWindow", "Nice"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.neck_min.setText(_translate("MainWindow", "-"))
        self.neck_plus.setText(_translate("MainWindow", "+"))
        self.head_min.setText(_translate("MainWindow", "-"))
        self.head_plus.setText(_translate("MainWindow", "+"))
        self.rollR_min.setText(_translate("MainWindow", "-"))
        self.rollR_plus.setText(_translate("MainWindow", "+"))
        self.shold2R_plus.setText(_translate("MainWindow", "+"))
        self.shold2R_min.setText(_translate("MainWindow", "-"))
        self.shold1R_plus.setText(_translate("MainWindow", "+"))
        self.shold1R_min.setText(_translate("MainWindow", "-"))
        self.armR_plus.setText(_translate("MainWindow", "+"))
        self.armR_min.setText(_translate("MainWindow", "-"))
        self.handR_plus.setText(_translate("MainWindow", "+"))
        self.handR_min.setText(_translate("MainWindow", "-"))
        self.rollL_plus.setText(_translate("MainWindow", "+"))
        self.rollL_min.setText(_translate("MainWindow", "-"))
        self.shold2L_plus.setText(_translate("MainWindow", "+"))
        self.shold2L_min.setText(_translate("MainWindow", "-"))
        self.shold1L_plus.setText(_translate("MainWindow", "+"))
        self.shold1L_min.setText(_translate("MainWindow", "-"))
        self.armL_plus.setText(_translate("MainWindow", "+"))
        self.armL_min.setText(_translate("MainWindow", "-"))
        self.handL_plus.setText(_translate("MainWindow", "+"))
        self.handL_min.setText(_translate("MainWindow", "-"))
        self.detach_all_Button.setText(_translate("MainWindow", "detach all"))
        self.detach_hands_Button.setText(_translate("MainWindow", "detach hands"))
        self.attach_all_Button.setText(_translate("MainWindow", "attach all"))
        self.save_Button.setText(_translate("MainWindow", "save"))
        self.next_Button.setText(_translate("MainWindow", "next"))
        self.label.setText(_translate("MainWindow", "Sence"))
        self.label_2.setText(_translate("MainWindow", "Distance"))
        self.label_3.setText(_translate("MainWindow", "Time"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.testButton.setText(_translate("MainWindow", "test"))
        __sortingEnabled = self.rateWidget.isSortingEnabled()
        self.rateWidget.setSortingEnabled(False)
        item = self.rateWidget.item(0)
        item.setText(_translate("MainWindow", "9600"))
        item = self.rateWidget.item(1)
        item.setText(_translate("MainWindow", "38400"))
        item = self.rateWidget.item(2)
        item.setText(_translate("MainWindow", "57600"))
        item = self.rateWidget.item(3)
        item.setText(_translate("MainWindow", "115200"))
        self.rateWidget.setSortingEnabled(__sortingEnabled)

